/*
**  LICENSE: BSD
**  Author: CandyMi[https://github.com/candymi]
**
** ccrandom.h — 128-bit and 256-bit non-cryptographic PRNGs.
**
** ============================================================================
** OVERVIEW
** ============================================================================
**
** Two engines, tuned for different trade-offs:
**
**   ccrandom128   Xoroshiro128++  2×u64 state,  2^128−1 period,  fastest.
**   ccrandom256   Xoshiro256**    4×u64 state,  2^256−1 period,  higher
**                                  statistical quality at a small throughput
**                                  cost.
**
** Both pass BigCrush (TestU01) and PractRand ≥ 32 TiB.  Seeded via
** SplitMix64 — any 64-bit seed maps to a well-distributed initial state.
**
** ============================================================================
** QUICK START
** ============================================================================
**
**   #include "ccrandom.h"
**
**   ccrandom128_t rng;
**   ccrandom128_init(&rng, 12345ULL);
**
**   uint64_t u = ccrandom128_next(&rng);      // [0, 2^64−1]
**   float    f = ccrandom128_f32next(&rng);   // [0, 1)
**   double   d = ccrandom128_f64next(&rng);   // [0, 1)
**
** ============================================================================
** API REFERENCE
** ============================================================================
**
**   void ccrandom128_init(ccrandom128_t *s, uint64_t seed)
**   void ccrandom256_init(ccrandom256_t *s, uint64_t seed)
**     Seed the generator.  Internally runs SplitMix64 twice (128) or four
**     times (256) to fill the state array — the user-provided seed is NOT
**     stored directly, so zero is a perfectly valid seed.
**
**   uint64_t ccrandom128_next(ccrandom128_t *s)
**   uint64_t ccrandom256_next(ccrandom256_t *s)
**     Return a uniformly-distributed 64-bit integer.  Advances the internal
**     state.  Not jump-ahead capable — use separate instances for
**     independent streams.
**
**   float  ccrandom128_f32next(ccrandom128_t *s)
**   float  ccrandom256_f32next(ccrandom256_t *s)
**     Return a float in [0, 1) with 24 bits of mantissa resolution.
**     Generated by taking the top 24 bits of a fresh u64 and multiplying
**     by 2^−24.
**
**   double ccrandom128_f64next(ccrandom128_t *s)
**   double ccrandom256_f64next(ccrandom256_t *s)
**     Return a double in [0, 1) with 53 bits of mantissa resolution.
**     Generated by taking the top 53 bits of a fresh u64 and multiplying
**     by 2^−53.
**
** ============================================================================
** THREAD SAFETY
** ============================================================================
**
**   None.  Each instance is an independent u64 array — caller must guard
**   concurrent access to the same state.  The recommended pattern is one
**   state per thread, seeded from a master generator or OS entropy.
**
** ============================================================================
** PORTABILITY
** ============================================================================
**
**   Language    C89 / C99 / C11 / C17 / C23,  C++98 / C++11 / C++14 / C++17 / C++20
**   Compilers   GCC ≥ 4.8,  Clang ≥ 3.4,  MSVC ≥ 2015,  ICC ≥ 19
**   Arch        any LP64 / LLP64 / ILP32 with 64-bit integer support
**
**   Requires <stdint.h> (C99 / C++11; MSVC 2010+ ships it).
**
**   Floating-point constants:  C99+ use 0x1.0p-N hex-float literals;
**   C89 and C++ < 17 fall back to the equivalent decimal value.  Both forms
**   constant-fold to the same IEEE 754 binary32/binary64 value.
**
** ============================================================================
** GUARANTEES & NON-GUARANTEES
** ============================================================================
**
**   Guaranteed:
**     • bit-identical output for a given seed on every supported compiler
**       and architecture (the state and transitions use only unsigned
**       64-bit arithmetic — no floating-point in the core).
**     • no dynamic allocation.
**
**   Not guaranteed:
**     • no backward-compatibility of output across versions.
**     • not suitable for cryptography — predictable from ~2^64 outputs.
**
** ============================================================================
** REFERENCES
** ============================================================================
**
**   [1] Blackman & Vigna, "Scrambled Linear Pseudorandom Number Generators",
**       ACM Trans. Math. Softw. 47(4), 2021.  <https://arxiv.org/abs/1805.01407>
**   [2] Vigna, "An experimental exploration of Marsaglia's xorshift generators,
**       scrambled", 2016.  <https://vigna.di.unimi.it/xorshift/>
**   [3] Steele & Vigna, "Computationally easy, spectrally good multipliers
**       for congruential PRNGs", 2021. <https://arxiv.org/abs/2001.05304>
**   [4] SplitMix64 — part of Java 8's SplittableRandom.
** ============================================================================
*/

#ifndef CCRANDOM_H
#define CCRANDOM_H

/* ── header dependencies ───────────────────────────────────────────────── */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── portable inline (C89 → C23, MSVC) ────────────────────────────────────
** ccalg convention: every container defines its own XXX_INLINE macro so that
** users can optionally replace `static inline` with `static` (C89) or
** compiler-specific keywords (MSVC __inline, GNU __inline__).                 */

#if   defined(__cplusplus) || (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)
# define CCRANDOM_INLINE static inline
#elif defined(_MSC_VER)
# define CCRANDOM_INLINE static __inline
#elif defined(__GNUC__) || defined(__clang__)
# define CCRANDOM_INLINE static __inline__
#else
# define CCRANDOM_INLINE static
#endif

#if defined(__cplusplus) && __cplusplus >= 201703L
  #define CCRANDOM_NOEXCEPT noexcept
#else
  #define CCRANDOM_NOEXCEPT
#endif

/* ── data types ─────────────────────────────────────────────────────────── */

typedef struct ccrandom128 { uint64_t seed[2]; } ccrandom128_t;
typedef struct ccrandom256 { uint64_t seed[4]; } ccrandom256_t;

/* ── internal helpers ─────────────────────────────────────────────────────
** Names prefixed ccr_ are implementation details.  Do not call directly.      */

CCRANDOM_INLINE uint64_t
ccr_rotl(const uint64_t x, unsigned int k) {
  /* k is always < 64 at every call site; the assert documents the contract
  ** and guards against accidental misuse.  */
  /* assert(k < 64);  -- enable during debug builds if you have <assert.h> */
  return (x << k) | (x >> (64 - k));
}

CCRANDOM_INLINE uint64_t
ccr_sm64_next(uint64_t *state) {
  /* SplitMix64 — a simple 64-bit mixing function with solid avalanche.
  ** Constants from Steele & Vigna [3]; multiplier 0x9e3779b97f4a7c15 is the
  ** fractional part of the golden ratio. */
  uint64_t z;
  z = (*state += UINT64_C(0x9e3779b97f4a7c15));
  z = (z ^ (z >> 30)) * UINT64_C(0xbf58476d1ce4e5b9);
  z = (z ^ (z >> 27)) * UINT64_C(0x94d049bb133111eb);
  return z ^ (z >> 31);
}

/* ── seed ───────────────────────────────────────────────────────────────── */

/** @brief Initialize a ccrandom128 generator with a 64-bit seed.
 *
 *  Internally runs SplitMix64 twice to produce a 128-bit state array.
 *  The original seed value is consumed (modified in-place), NOT stored
 *  directly — so zero is a perfectly valid seed.
 *
 *  After init the generator is ready for ccrandom128_next, _f32next, _f64next.
 *  No dynamic allocation.
 *
 *  @param state  Generator state to initialize (must not be NULL).
 *  @param seed   Any 64-bit value; zero is valid. */
CCRANDOM_INLINE void
ccrandom128_init(ccrandom128_t *state, uint64_t seed) CCRANDOM_NOEXCEPT {
  /* Map a user seed to a 128-bit state via two iterations of SplitMix64.
  ** The seed is consumed (modified in-place) so zero-initialized seeds work. */
  state->seed[0] = ccr_sm64_next(&seed);
  state->seed[1] = ccr_sm64_next(&seed);
}

/** @brief Initialize a ccrandom256 generator with a 64-bit seed.
 *
 *  Internally runs SplitMix64 four times to produce a 256-bit state array.
 *  The original seed value is consumed (modified in-place), NOT stored
 *  directly — so zero is a perfectly valid seed.
 *
 *  After init the generator is ready for ccrandom256_next, _f32next, _f64next.
 *  No dynamic allocation.
 *
 *  @param state  Generator state to initialize (must not be NULL).
 *  @param seed   Any 64-bit value; zero is valid. */
CCRANDOM_INLINE void
ccrandom256_init(ccrandom256_t *state, uint64_t seed) CCRANDOM_NOEXCEPT {
  state->seed[0] = ccr_sm64_next(&seed);
  state->seed[1] = ccr_sm64_next(&seed);
  state->seed[2] = ccr_sm64_next(&seed);
  state->seed[3] = ccr_sm64_next(&seed);
}

/* ── 64-bit integer output ─────────────────────────────────────────────── */

/** @brief Draw the next 64-bit integer from a ccrandom128 (Xoroshiro128++).
 *
 *  Advances the internal state by one step.  Not jump-ahead capable —
 *  use separate instances for independent streams.
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed value in [0, 2^64−1]. */
CCRANDOM_INLINE uint64_t
ccrandom128_next(ccrandom128_t *state) CCRANDOM_NOEXCEPT {
  /* Xoroshiro128++  —  the "++" scrambler provides a small decorrelation
  ** improvement over the plain "+" variant (fails only linearity tests
  ** reversed from the output, which no realistic workload triggers). */
  const uint64_t s0 = state->seed[0];
        uint64_t s1 = state->seed[1];
  const uint64_t result = ccr_rotl(s0 + s1, 17) + s0;

  s1 ^= s0;
  state->seed[0] = ccr_rotl(s0, 49) ^ s1 ^ (s1 << 21);
  state->seed[1] = ccr_rotl(s1, 28);

  return result;
}

/** @brief Draw the next 64-bit integer from a ccrandom256 (Xoshiro256**).
 *
 *  Advances the internal state by one step.  Higher statistical quality
 *  (passes BigCrush and PractRand ≥ 32 TiB) at a small throughput cost
 *  vs ccrandom128.
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed value in [0, 2^64−1]. */
CCRANDOM_INLINE uint64_t
ccrandom256_next(ccrandom256_t *state) CCRANDOM_NOEXCEPT {
  /* Xoshiro256**  —  the "**" scrambler (multiply-rotate-multiply) yields
  ** excellent statistical quality. */
  const uint64_t result = ccr_rotl(state->seed[1] * 5, 7) * 9;

  const uint64_t t = state->seed[1] << 17;

  state->seed[2] ^= state->seed[0];
  state->seed[3] ^= state->seed[1];
  state->seed[1] ^= state->seed[2];
  state->seed[0] ^= state->seed[3];

  state->seed[2] ^= t;
  state->seed[3] = ccr_rotl(state->seed[3], 45);

  return result;
}

/* ── floating-point constants ─────────────────────────────────────────────
**
** 2^−53 and 2^−24, exactly representable in IEEE 754 binary32 / binary64.
**
** Hex-float literals (0x1.0p-N) are standard C99 but only C++17.  When
** compiling as C++ < C++17 we fall back to the equivalent decimal value;
** modern compilers constant-fold both to identical machine code.              */

#if defined(__cplusplus) && __cplusplus < 201703L
# define CCRANDOM_F64_MUL (1.0 / 9007199254740992.0)   /* 2^-53 */
# define CCRANDOM_F32_MUL (1.0f / 16777216.0f)          /* 2^-24 */
#else
# define CCRANDOM_F64_MUL 0x1.0p-53
# define CCRANDOM_F32_MUL 0x1.0p-24f
#endif

/* ── floating-point output ────────────────────────────────────────────────
**
** Strategy:  take the *top* N bits of a fresh u64 and multiply by 2^−N.
**
**   float  ← top 24 bits → multiply by 2^−24
**   double ← top 53 bits → multiply by 2^−53
**
** Why top bits?  u64 → f64 discards 11 of 64 bits of entropy — if we took
** the *lower* bits those 11 would be lost AND the remaining 53 would be
** biased by the discarded portion.  Using the *upper* bits (via >>) keeps
** the conversion lossless.
** ========================================================================== */

/** @brief Draw the next float in [0, 1) from a ccrandom128 generator.
 *
 *  Takes the top 24 bits of a fresh ccrandom128_next() output and
 *  multiplies by 2^−24.  Resolution is 24 bits of mantissa
 *  (≈ 1.19e−7 granularity).
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed float in [0, 1). */
CCRANDOM_INLINE float
ccrandom128_f32next(ccrandom128_t *state) CCRANDOM_NOEXCEPT {
  return (float)((ccrandom128_next(state) >> 40) * CCRANDOM_F32_MUL);
}

/** @brief Draw the next float in [0, 1) from a ccrandom256 generator.
 *
 *  Takes the top 24 bits of a fresh ccrandom256_next() output and
 *  multiplies by 2^−24.  Resolution is 24 bits of mantissa
 *  (≈ 1.19e−7 granularity).
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed float in [0, 1). */
CCRANDOM_INLINE float
ccrandom256_f32next(ccrandom256_t *state) CCRANDOM_NOEXCEPT {
  return (float)((ccrandom256_next(state) >> 40) * CCRANDOM_F32_MUL);
}

/** @brief Draw the next double in [0, 1) from a ccrandom128 generator.
 *
 *  Takes the top 53 bits of a fresh ccrandom128_next() output and
 *  multiplies by 2^−53.  Resolution is 53 bits of mantissa
 *  (≈ 1.11e−16 granularity).
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed double in [0, 1). */
CCRANDOM_INLINE double
ccrandom128_f64next(ccrandom128_t *state) CCRANDOM_NOEXCEPT {
  return (double)((ccrandom128_next(state) >> 11) * CCRANDOM_F64_MUL);
}

/** @brief Draw the next double in [0, 1) from a ccrandom256 generator.
 *
 *  Takes the top 53 bits of a fresh ccrandom256_next() output and
 *  multiplies by 2^−53.  Resolution is 53 bits of mantissa
 *  (≈ 1.11e−16 granularity).
 *
 *  @param state  Generator state (must not be NULL).
 *
 *  @return A uniformly-distributed double in [0, 1). */
CCRANDOM_INLINE double
ccrandom256_f64next(ccrandom256_t *state) CCRANDOM_NOEXCEPT {
  return (double)((ccrandom256_next(state) >> 11) * CCRANDOM_F64_MUL);
}

#undef CCRANDOM_F64_MUL
#undef CCRANDOM_F32_MUL

#ifdef __cplusplus
}
#endif

#endif /* CCRANDOM_H */
